config_data = {}
config_data['app_name'] = 'pdb'
config_data['dbname'] = 'pdbdatabase'
config_data['dbuser'] = 'pdb'
config_data['dbpass'] = 'hunter2'
config_data['dbhost'] = 'localhost'
config_data['ip'] = '127.0.0.1'
config_data['port'] = 5000
config_data['supported_langs'] = ['en', 'nl']
config_data['loginMode']='ldap' #can be normal and ldap
