config_data = {}
config_data['app_name'] = 'pdb'
config_data['dbname'] = 'pdbdatabase'
config_data['dbuser'] = 'pdb'
config_data['dbpass'] = 'hunter2'
config_data['dbhost'] = 'localhost'
config_data['ip'] = '127.0.0.1'
config_data['port'] = 5000
config_data['supported_langs'] = ['en', 'nl']
config_data['loginMode'] = 'normal'  # can be normal and ldap
config_data['calc_tags'] = False #warning: setting this to true will remove all current tags the next time you start up
config_data['debug'] = True
