from App.base import *
from App.administration import *
from App.bookmarks import *
from App.home import *
from App.people import *
from App.profile import *
from App.projects import *
from App.researchgroups import *
from App.utilities import *