DROP TABLE IF EXISTS sessionProjectClick;
DROP TABLE IF EXISTS sessionSearchQuery;
DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS bookmark;
DROP TABLE IF EXISTS projectRegistration;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS projectDocument;
DROP TABLE IF EXISTS projectRelation;
DROP TABLE IF EXISTS projectTag;
DROP TABLE IF EXISTS projectPromotor;
DROP TABLE IF EXISTS projectTypeConnection;
DROP TABLE IF EXISTS projectType;
DROP TABLE IF EXISTS projectYearConnection;
DROP TABLE IF EXISTS projectYear;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS contactPerson;
DROP TABLE IF EXISTS employeeRoles;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS groupDescription;
DROP TABLE IF EXISTS researchGroup;
DROP TABLE IF EXISTS attachment;
DROP TABLE IF EXISTS document;
drop table if exists discipline;
drop table if exists language;
drop table if exists title;
drop table if exists intext;
drop table if exists typeResearch;
drop table if exists registration;
DROP DOMAIN IF EXISTS language;
DROP DOMAIN IF EXISTS registration;
DROP DOMAIN IF EXISTS typeResearch;
DROP DOMAIN IF EXISTS INTEXT;
DROP DOMAIN IF EXISTS title;
DROP DOMAIN IF EXISTS subject;

drop database pdbdatabase;
drop role pdb;