insert into projectTypeConnection (project_id, type_id) values (1,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (3,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (4,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (5,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (6,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (7,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (9,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (13,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (14,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (15,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (16,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (20,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (21,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (22,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (23,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (24,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (25,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (26,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (27,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (28,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (40,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (41,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (42,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (43,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (44,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (46,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (47,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (48,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (49,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (52,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (53,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (56,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (57,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (58,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (59,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (60,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (62,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (64,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (67,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (70,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (72,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (73,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (74,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (75,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (76,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (77,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (78,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (79,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (80,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (92,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (97,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (99,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (100,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (104,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (107,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (108,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (110,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (113,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (114,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (115,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (116,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (117,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (118,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (120,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (123,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (124,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (125,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (126,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (127,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (128,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (129,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (133,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (135,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (137,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (143,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (145,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (147,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (150,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (152,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (153,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (156,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (157,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (158,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (159,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (160,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (161,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (162,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (163,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (165,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (167,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (168,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (170,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (171,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (172,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (173,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (174,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (175,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (177,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (178,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (179,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (180,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (182,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (183,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (190,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (203,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (206,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (211,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (212,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (213,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (215,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (219,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (220,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (221,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (222,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (223,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (224,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (225,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (226,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (227,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (231,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (234,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (235,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (236,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (237,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (238,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (241,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (246,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (250,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (252,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (254,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (256,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (258,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (261,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (262,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (263,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (264,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (265,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (266,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (272,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (275,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (276,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (278,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (279,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (280,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (281,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (282,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (283,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (286,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (294,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (295,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (296,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (299,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (306,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (309,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (310,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (311,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (317,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (320,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (321,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (322,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (323,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (324,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (325,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (329,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (330,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (331,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (338,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (342,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (347,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (362,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (367,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (371,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (372,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (373,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (377,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (378,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (379,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (380,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (381,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (382,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (383,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (385,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (392,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (394,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (402,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (403,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (404,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (407,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (408,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (418,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (420,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (421,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (422,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (423,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (429,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (430,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (441,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (442,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (443,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (444,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (445,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (457,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (458,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (459,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (461,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (464,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (465,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (466,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (472,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (473,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (479,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (480,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (481,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (490,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (491,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (493,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (498,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (500,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (501,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (505,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (506,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (509,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (514,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (515,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (517,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (518,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (519,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (525,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (526,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (529,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (531,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (533,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (534,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (535,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (536,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (541,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (542,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (543,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (556,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (557,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (559,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (561,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (562,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (563,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (564,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (565,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (566,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (568,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (570,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (571,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (574,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (577,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (578,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (583,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (584,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (587,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (588,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (591,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (595,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (596,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (597,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (598,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (599,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (602,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (605,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (606,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (608,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (611,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (612,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (613,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (614,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (615,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (617,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (623,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (626,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (627,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (629,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (636,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (637,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (639,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (641,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (643,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (644,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (656,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (657,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (658,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (659,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (660,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (662,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (663,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (664,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (665,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (666,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (677,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (687,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (684,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (630,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (693,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (697,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (698,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (699,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (661,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (700,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (624,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (703,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (703,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (706,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (679,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (708,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (709,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (530,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (579,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (711,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (645,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (716,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (637,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (637,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (637,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (636,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (621,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (713,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (713,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (713,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (714,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (715,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (544,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (719,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (719,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (719,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (721,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (720,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (720,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (716,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (716,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (132,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (726,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (726,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (726,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (732,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (734,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (734,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (688,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (685,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (685,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (742,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (747,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (748,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (749,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (732,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (732,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (723,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (754,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (756,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (757,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (737,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (759,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (760,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (761,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (638,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (763,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (763,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (764,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (707,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (653,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (765,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (622,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (622,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (715,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (715,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (636,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (636,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (712,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (778,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (516,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (253,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (492,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (671,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (669,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (154,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (508,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (112,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (670,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (676,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (668,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (507,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (460,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (437,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (45,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (798,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (799,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (690,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (796,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (801,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (797,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (724,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (639,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (639,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (640,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (528,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (805,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (806,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (807,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (808,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (809,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (811,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (811,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (346,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (686,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (532,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (814,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (769,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (714,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (714,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (766,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (820,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (768,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (768,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (767,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (772,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (839,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (839,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (839,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (840,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (844,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (844,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (846,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (847,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (625,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (691,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (851,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (852,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (853,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (854,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (855,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (762,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (762,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (447,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (448,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (582,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (823,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (867,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (867,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (868,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (878,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (878,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (882,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (882,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (883,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (888,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (891,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (873,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (873,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (896,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (898,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (898,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (897,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (897,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (899,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (655,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (901,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (901,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (901,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (904,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (904,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (904,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (908,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (909,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (909,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (909,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (911,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (910,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (865,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (865,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (912,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (743,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (504,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (576,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (592,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (455,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (616,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (628,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (813,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (642,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (914,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (914,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (654,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (919,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (920,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (922,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (922,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (922,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (923,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (924,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (925,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (926,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (927,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (927,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (927,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (888,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (888,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (929,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (900,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (781,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (780,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (785,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (880,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (880,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (428,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (439,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (503,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (702,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (819,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (779,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (783,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (784,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (842,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (842,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (830,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (830,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (829,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (829,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (771,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (771,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (770,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (770,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (721,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (721,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (537,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (733,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (730,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (883,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (883,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (826,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (826,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (874,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (874,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (874,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (934,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (935,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (938,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (938,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (939,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (939,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (940,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (941,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (654,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (654,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (942,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (943,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (943,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (943,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (945,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (945,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (840,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (840,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (694,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (580,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (845,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (948,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (843,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (955,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (955,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (955,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (956,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (957,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (958,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (961,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (485,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (955,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (962,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (963,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (964,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (965,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (968,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (968,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (968,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (966,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (966,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (967,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (967,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (969,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (969,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (970,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (970,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (971,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (971,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (965,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (965,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (973,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (975,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (976,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (875,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (875,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (920,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (920,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (919,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (919,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (936,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (937,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (937,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (916,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (916,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (959,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (977,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (978,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (979,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (982,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (849,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (849,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (933,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (933,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (929,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (929,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (983,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (985,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (915,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (915,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (876,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (876,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (918,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (918,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (986,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (986,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (987,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (988,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (988,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (988,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (486,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (673,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (674,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (675,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (673,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (673,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (674,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (674,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (675,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (675,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (553,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (866,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (940,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (940,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (941,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (941,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (991,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (991,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (991,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (992,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (994,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (552,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (553,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (553,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (995,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (935,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (935,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (934,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (934,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (996,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (996,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (996,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (997,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (997,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (997,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (995,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (995,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (994,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (994,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (998,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1002,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (839,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (946,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1005,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1005,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1007,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1009,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1008,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1010,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1011,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1012,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1017,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1017,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1017,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1018,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1018,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1018,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1014,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1020,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1024,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1025,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (998,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (998,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (999,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (999,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1028,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1028,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1030,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1030,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1031,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1031,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1031,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1033,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (958,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (958,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (957,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (957,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (992,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (992,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (908,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (908,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (483,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (765,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (765,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1037,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1036,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1036,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (956,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (956,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1037,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1037,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (960,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (838,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1040,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1041,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (948,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (948,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (950,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1035,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (902,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1040,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1040,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1043,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1043,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1043,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1045,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (944,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1046,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1046,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1046,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (857,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1048,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1049,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (982,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (982,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (979,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (979,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (877,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (877,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (980,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1013,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1013,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1014,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1014,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1047,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (973,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (973,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (976,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (976,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1004,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1004,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1006,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1006,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1007,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1007,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (917,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1019,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1050,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1050,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1059,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1062,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1062,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1063,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1063,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1064,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1064,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1065,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1065,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1067,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1067,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1070,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1071,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1071,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1073,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1073,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1074,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1074,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1075,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1075,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1079,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1079,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1080,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1081,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1082,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1082,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1083,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1083,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1084,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1084,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1085,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1085,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1086,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1086,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1087,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1087,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1088,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1088,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1052,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1052,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (963,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (963,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (962,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (962,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (964,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (964,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (974,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (974,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1001,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1003,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1012,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1012,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1015,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1069,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1069,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1055,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1055,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1057,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1058,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1058,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1089,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1090,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1090,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1091,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1091,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1092,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1092,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1093,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1093,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1094,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1094,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1095,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1095,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1096,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1096,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1098,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1098,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1099,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1099,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1100,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1100,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1101,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1101,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1102,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1102,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1103,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1103,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1104,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1104,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1105,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1106,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1107,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1107,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1107,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1033,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1033,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1108,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1110,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1110,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1110,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1111,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1111,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1111,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1112,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1114,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1115,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1115,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1023,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1023,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1108,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1108,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1109,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1109,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1027,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1026,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1021,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1022,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1113,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1113,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (696,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (952,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1112,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1112,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (975,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (975,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1116,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (1116,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1116,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1116,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1117,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1118,'Bachelor dissertation');
insert into projectTypeConnection (project_id, type_id) values (1118,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1118,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1118,'Research internship 2');
insert into projectTypeConnection (project_id, type_id) values (1038,'Master thesis');
insert into projectTypeConnection (project_id, type_id) values (1039,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1041,'Research internship 1');
insert into projectTypeConnection (project_id, type_id) values (1041,'Research internship 2');
