insert into project (projectID, title, maxStudents, active) values (1,'PROTOTYPE XML DOCUMENT SERVER',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (3,'MODELLEREN VAN MPEG-2 VIDEO BRONNEN',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (4,'INVLOED VAN HET DISTRIBUTIEPROCES OP DE PERFORMANTIE VAN EEN CDN EN OP DE SIGNALING OVERHEAD',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (5,'SCHEDULING MECHANISMES VOOR AUDIO EN VIDEO STROMEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (6,'TOOL VOOR SEMANTISCHE TABLEAUS IN JAVA',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (7,'GUI BOVENOP ANT-BUILD TOOL',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (9,'REDACTIESYSTEEM STUDENTENBLAD <I>DWARS</I>',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (13,'TRAFFIC GENERATOR',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (14,'ORGANISATIESYSTEEM VOOR FINE FLEUR, HET KOOR VAN DE NIGHT OF THE PROMS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (15,'QUIZSITE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (16,'SOFTWARE VOOR EDUCATIE EN COMMUNICATIE VOOR KINDEREN MET AUTISME.',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (20,'C++ TEMPLATES VOOR DE EFFICIENTE IMPLEMENTATIE VAN INTERVAL ARITMETIEK',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (21,'JOURNALWATCH V2.0',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (22,'QT# VOOR PIM V4.0',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (23,'RADIALE BASIS FUNCTIES: ALGORITMES EN TOEPASSINGEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (24,'AUTOMATISCHE DIFFERENTIATIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (25,'TEMPLATED BLAS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (26,'CROSS-PLATFORM REGISTRATIE- EN FACTURATIESYSTEEM',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (27,'ELEKTRONISCH TIJDSCHRIFT',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (28,'BEKNOPTE REPRESENTATIES VOOR FREQUENT SET MINING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (40,'VALIDATIE VAN FLOATING-POINT UNITS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (41,'DETECTIE VAN SINGULARITEITEN IN MULTIVARIATE MODELLEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (42,'CELL LOSS PROBABILITY BENADERING BIJ GEMETEN DATA',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (43,'EINDWERKEN AGFA-GEVAERT (2005)',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (44,'EVALUATIE MAPLE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (45,'Verificatie van de implementatie van IEEE conforme functies',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (46,'PARALLELLISEREN VAN EEN C++ KLASSE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (47,'VORMRECONSTRUCTIE OP BASIS VAN MOMENTENINFORMATIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (48,'TESTINGTOOL VOOR DECIMAAL <-> BINAIRE CONVERSIE',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (49,'VIRTUAL OFFICE PROJECT',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (52,'EVALUATIE OP BASIS VAN CAUSALE BOOMSTRUCTUREN VOOR PARTITIES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (53,'BETROUWBARE CALCULATOR EN GRAPHICS TOOL VOOR COMPLEXE VERANDERLIJKEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (56,'SYSTEEM VOOR DE ONTVANGST EN VERWERKING VAN METEOSAT-WOLKENFOTO ''S',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (57,'PROGRAMMEREN VAN EEN MICROCONTROLLER VOOR ROBOTSTURING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (58,'EEN SOFTBOT VOOR DOCUMENTCLASSIFICATIE : LEARNING TOEGEPAST',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (59,'CONSTRAINT SATISFACTION ALGORITMES VOOR SCHEDULING, ALLOCATIE VAN RESOURCES, ...',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (60,'GEDISTRIBUEERDE NETWERK MONITORING TOOL',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (62,'VIDEORESERVATIESYSTEEM',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (64,'INFORMATION RETRIEVAL VOOR ARTSEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (67,'MANAGING PRESENTATION TIER EVOLUTION USING CODE GENERATORS (EXTENDED VERSION)',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (70,'MANAGING PRESENTATION TIER EVOLUTION USING CODE GENERATORS (BASIC VERSION)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (72,'INVERTEREN VAN TWEEVOUDIG KANSGENERERENDE FUNCTIES MET TOEPASSING OP VOORBEELDEN UIT DE WACHTRIJTHEORIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (73,'MULTICAST IN EEN CONTENT DISTRIBUTIE NETWERK',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (74,'CAC VOOR VIDEO STROMEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (75,'XSL-FO FORMATTER VOOR PDA''S',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (76,'BEVEILIGEN VAN JAVA PROGRAMMA''S TEGEN COPIEREN EN DECOMPILEREN',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (77,'XSLT EXTENSIES STANDARDISEREN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (78,'FONT LIBRARY IN JAVA',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (79,'VERGELIJKENDE STUDIE VAN DISCRETE EVENT SIMULATIEPAKKETTEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (80,'ANALYSE EN STUDIE ROND NETWERKBEVEILIGING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (92,'MULTICAST VAN LIVE TV',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (97,'DATA MINING: ROLL-UP DEPENDENCIES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (99,'TCP''S REACTION TO MOBILITY',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (100,'MODELLERING VAN EXTINCTIEPATRONEN IN VEGETATIES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (104,'INTEGRATIE CRM-PAKKET MET MYSQL & PHP',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (107,'IMPLEMENTATIE EN EVALUATIE VAN AD-HOC ON-DEMAND DISTANCE VECTOR ROUTING (AODV)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (108,'INTEGRATIE ACCESS-APPLICATIES MET MYSQL & PHP',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (110,'SUPPORT VECTOR MACHINES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (112,'Modellering in nieuwe technologische toepassingen',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (113,'ONTWIKKELEN VAN EEN MULTIPRECIEZE POLYNOMIALE ROOT SOLVER',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (114,'UITBREIDING VAN DE IEEECC754 COMPLIANCE CHECKER (oud)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (115,'DATABASE SUPPORT VOOR DATA MINING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (116,'MEDIUM ACCESS CONTROL PROTOCOLLEN VOOR BODY AREA NETWERKEN (BAN)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (117,'LEARNING EN INFORMATIE-EXTRACTIE TOEGEPAST: EEN SOFTBOT VOOR HET BEHEER VAN DATA IN EEN PIM',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (118,'VORMRECONSTRUCTIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (120,'KARAKTERISATIE VAN 3D OBJECTEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (123,'AUDIO: DIGITAL AUDIO EFFECTS (DAFX)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (124,'AUDIO: MPEG-4 STRUCTURED AUDIO',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (125,'AUDIO: MODEL BASED AUDIO PROCESSING (MBAP)',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (126,'INFORMATIE EXTRACTIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (127,'LIMITS OF INPUT-QUEUED SWITCH PERFORMANCE WITH FUTURE PACKET ARRIVAL INFORMATION',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (128,'WAITING TIME AND QUEUE LENGTH DISTRIBUTION OF IMPATIENT CUSTOMERS IN AN D-MAP/PH/1 QUEUE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (129,'ALGORITMES VOOR CONSTRAINT SATISFACTION PROBLEMEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (132,'CONSISTENTIE VAN UML DIAGRAMMEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (133,'SMARTPHONE DATA SYNCHRONISATION EN DEVICE MANAGEMENT',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (135,'METHODEN VOOR DE HERKENNING VAN EEN NIET-ELEKTRONISCHE HANDTEKENING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (137,'SOFTWARE VOOR EDUCATIE EN COMMUNICATIE VOOR KINDEREN MET AUTISME',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (143,'AUTOMATISATIE VAN GRAFISCH ONTWERP',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (145,'SINUSITIS DATABASE PROJECT',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (147,'ROBOTICA',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (150,'GRAFISCHE REPRESENTATIE VAN EEN SEMANTISCH NETWERK',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (152,'DATABASE MODULE FOR CONCURRENT XML AUTHORING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (153,'MULTIPRECISIE HYPERGEOMETRISCHE FUNCTIES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (154,'Implementatie van widest-needed evaluation',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (156,'MULTIPRECISIE BEREKENING VAN WISKUNDIGE CONSTANTEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (157,'METAPOST GRAPHICS EN TEX STYLEFILE SCRIPTS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (158,'SOFTBOT OP ZOEK NAAR BIBTEX VELDEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (159,'VEHICLE ROUTING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (160,'SPECTRALE ANALYSE VAN PRINT PROCESSEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (161,'CLIENT-SERVER IMPLEMENTATIE VAN EEN CROSS-PLATFORM WETENSCHAPPELIJKE REKENOMGEVING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (162,'DEBUGGEN EN TESTEN VAN ARITHMETISCHE SOFTWARE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (163,'TOPOLOGY-BASED NETWORK MONITORING TOOL',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (165,'WEB MINING',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (167,'CLASS LIBRARY VOOR POLYNOMIALE ARITMETIEK',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (168,'INFORMATIESYSTEEM LOKALE POLITIE ST-NIKLAAS',3,FALSE);
insert into project (projectID, title, maxStudents, active) values (170,'PRESENCE PROTOCOL VOOR EMAIL',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (171,'EEN ODF PLUG-IN VOOR FIREFOX',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (172,'2D/3D MAP VISUALIZATION AND PATH GENERATION',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (173,'WEBAPPLICATIE VOOR GEDISTRIBUEERD ALUMNI-BEHEER',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (174,'WOORDENBOEK VOOR VLAAMSE GEBARENTAAL',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (175,'Refactoring van een bestaande QT-applicatie',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (177,'XML DOCUMENT PROJECTIE',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (178,'XQUERY/XPATH VERTALING NAAR SQL - HET <I>NODE IDENTITEIT EN DOCUMENT VOLGORDE</I> PROBLEEM',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (179,'WEB 2.0 APPLICATIE VOOR DAGBOEK GEBASEERD FOTO BEHEER',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (180,'INFORMATION MASHUPS : DBWORLD COMBINEREN MET GOOGLE CALENDAR EN GOOGLE MAPS',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (182,'GECENTRALISEERDE NETWERKANALYSE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (183,'AJAX MINDMAPPING APPLICATIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (190,'ACTUALISATIE ARCHEOLOGISCH ARCHIEFSYSTEEM STAD ANTWERPEN',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (203,'FIBONACCI HEAPS: AN INGENIOUS DATA STRUCTURE FOR IMPLEMENTING NETWORK OPTIMIZATION ALGORITHMS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (206,'Extending an open source modeling (UML) tool',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (211,'UITBREIDING VAN DE JAVA WEKA DATA MINING LIBRARY',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (212,'SFERISCHE REPRESENTATIE VAN DE MENSELIJKE CORTEX VOOR DE VISUALISATIE EN ANALYSE VAN FMRI-DATA',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (213,'XML QUERY ALGEBRA''S',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (215,'VISUALISATIE TOOL VOOR MOBILITEITSTESTBED',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (219,'AUTOMATISATIE VAN CITATIERAPPORTEN VOOR DE UA ONDERZOEKSRAAD',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (220,'LIBRARY COMPARISON TESTER',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (221,'MULTIPRECISIE MATLAB KERNEL',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (222,'INVLOED VAN SLIPPEN OP HET AFGELEGDE TRAJECT',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (223,'CONVERSIE VAN TEKSTDOCUMENTEN NAAR FEATUREVECTOREN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (224,'ONLINE ENQUETE SOFTWARE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (225,'DUBBELE CLASSIFICATIE VOOR INFORMATIE EXTRACTIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (226,'STATISTISCHE VORMANALYSE VAN BIOLOGISCHE OBJECTEN VAN WILLEKEURIGE TOPOLOGIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (227,'ADDRESS AUTOCONFIGURATION FOR MOBILE AD HOC NETWORKS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (231,'PROGRAMMEERPARADIGMA''S / DYNAMISCHE TALEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (234,'SENSOR NETWORKS: SIMULATION TOOLS FOR ANALYSING REAL NETWORK CODE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (235,'INVLOED VAN SLIPPEN OP ROBOTLOCALISATIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (236,'GEDISTRIBUEERDE MULTIPRECISIE BEREKENING VAN WISKUNDIGE CONSTANTEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (237,'LEVEL SET METHODES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (238,'MULTIRELATIONAL DATA MINING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (241,'Vergelijking van METACASE tools (GMF, TOPMODL, GENGED, ATOM3, TIGER etc.)',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (246,'Eindwerken Dow Chemical',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (250,'MINING IN PEER TO PEER NETWORKS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (252,'EXTRACTION OF PATTERN CONSTRAINTS FROM SQL QUERIES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (253,'Debuggen en testen van een softwarebibliotheek',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (254,'PLAATSING VAN SPELKAARTEN OP EEN DRUKVEL',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (256,'Implementatie van UML refactorings met MoTMoT',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (258,'SEGMENTATIE VAN 3D-OBJECTEN A.H.V. STATISTISCHE VORMMODELLEN',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (261,'MINING DYNAMIC PATHS IN A GRAPH',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (262,'REMOTE DATA SYNCHRONISATION.',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (263,'REMOTE DEVICE MANAGEMENT.',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (264,'JAVA JAR VERSIES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (265,'HIGH PERFORMANCE WEB SERVICES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (266,'ONDERZOEK EN DEMONSTRATIEONTWIKKELING VAN EEN SERVER-SIDE SMARTCARD AANSTURING.',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (272,'ESP ON RAILS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (275,'TILE MINING ALGORTIME IMPLEMENTATIE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (276,'MKG REGISTRATIE',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (278,'ONDERZOEK NAAR PERSISTENTIE-FRAMEWORKS:',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (279,'VERGELIJKEND ONDERZOEK VAN DE (UNIT-)TESTBAARHEID VAN DIVERSE JAVA APPLICATIE ONTWIKKELINGS FRAMEWORKS',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (280,'CLICK DEVELOP',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (281,'ANALYSE VAN HET UA WIRELESS NETWERK',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (282,'TERRAN TESTBED DEVELOPMENT FEATURES',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (283,'TERRAN TESTBED GOES MOBILE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (286,'SECURITY IN AD HOC NETWORKS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (294,'SOFTWARE ENGINEERING PRINCIPLES IN CLICK',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (295,'MACHINE LEARNING TECHNIEKEN VOOR FEATURE-SUBSET SELECTIE: THEORIE EN TOEPASSINGEN',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (296,'DESIGN OF AN ADVANCED TESTBED - PC VIRTUALIZATION',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (299,'ONTWIKKELING VAN EEN NETWORK VISUALIZER',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (306,'ANALYSE VAN HET PAKKET VERLIES PROCES IN EEN WACHTRIJ MODEL',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (309,'OPTIMALISATIE VAN SONAR SENSOREN IN ROBOTICA',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (310,'Evaluatie van een visuele debugging tool (eDOBS)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (311,'VOORWERP IDENTIFICATIE EN LOKALISATIE OP BASIS VAN SONAR DATA IN ROBOTS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (317,'DE EEKHOORN EN HET STUDENTENBLAD',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (320,'PROFESSIONALISERING VAN DE LIBRA TOOLBOX',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (321,'EEN GEBARENWOORDENBOEK OP MVC EN DVD',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (322,'PORTING LINUX AND LINUX KERNEL DRIVER DEVELOPMENT ON A CUSTOM ARM11 BASED SOC (SYSTEM ON CHIP) FOR DIGITAL VIDEO RECEPTION/DECODING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (323,'ADVANCED DATA STRUCTURES FOR NETWORK OPTIMIZATION PROBLEMS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (324,'RANK-CORRELATED SET MINING ALGORITME IMPLEMENTATIE',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (325,'GENERIC SOCIAL RECOMMENDATION SYSTEM',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (329,'MODELING THROUGH SCENARIO BASED TESTING',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (330,'EINDWERKEN AGFA-GEVAERT',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (331,'EINDWERKEN AGFA-GEVAERT (2006)',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (338,'A WEBSERVER LOG ANALYZER FRAMEWORK',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (342,'Ju-jitsu kampioenschap organisator',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (346,'APPLICATION GENERATION SUPPORT TOOL',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (347,'Synchronisatie Contacts & Calendar',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (362,'AGGREGATED OPEN SOCIAL NETWORK met Microformats',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (367,'Artificial Neural Network editor/visualization tool',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (371,'Lessenrooster Web Services',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (372,'Een web-gebaseerd invoer systeem voor observaties van vuurbollen',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (373,'Intrusion Detection in Databases',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (377,'Implementatie van een aspect-taal met parent-introductie op een aspect VM',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (378,'Performance van een aspect VM',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (379,'Support for thread-local aspect-deployment in our aspect VM',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (380,'SunSPOTs on DYMO',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (381,'Adapting the SunSPOT architecture for MAC development',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (382,'Developing a self recovering, watchdog based SunSPOT testbed',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (383,'Optimalisatie van de kosten bij intermodaal transport ',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (385,'Controlled Graph Transformation in AToM3',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (392,'SunSPOTs and PCAP',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (394,'De implementatie van een client en een server voor een Collaborative Editing System',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (402,'Research Website on Drupal',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (403,'ESP on Drupal',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (404,'Eclipse Plugin for Click Development',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (407,'Ricochet Robots Metacompetitie',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (408,'Ricochet Robots Stats op Google App Engine',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (418,'Ontwikkeling van een gedistribueerde installer voor het CoBRA grid',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (420,'Toevoegen van een op predictie gebaseerde scheduling techniek binnen GridSim',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (421,'IPv4 - IPv6 conversie',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (422,'TCP flavours',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (423,'802.11 e',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (428,'SunSPOT profiling',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (429,'Firewall SImulatie Tool voor Shorewall/IPTables',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (430,'Porting nsclick to ns-3',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (437,'Uitbreiding van de IeeeCC754 compliance checker',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (439,'Betrouwbare broadcasts in sensornetwerken',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (441,'Tools for effective multi-objective optimization using swarm intelligence',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (442,'Tools for effective multi-criteria optimization using swarm intelligence',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (443,'Space-filling designs computed on GPUs',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (444,'Efficient tools for effective optimization using swarm intelligence',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (445,'Tools for effective function optimization using swarm intelligence',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (447,'Performance Analysis of WSDM-enabled Web Services',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (448,'NetBeans plugin for WSDM SOA project',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (455,'An adaptive OSGi robotic application',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (457,'Context Aware Adaptation Framework with application on Lego Robot',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (458,'Multicast/Broadcast Transparency in Wireless Mesh Networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (459,'Service Redundancy in Wireless Mesh Networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (460,'Uitbreiden van JabRef  (open source Java programma)',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (461,'Uplink pakket scheduling in LTE',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (464,'Wireshark generic dissector: cross platform',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (465,'Testen van FPU van een GPU',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (466,'Radio Simulation in Solarium',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (472,'Implementing an MDSOC virtual machine in Maxine',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (473,'an MDSOC Virtual Machine as execution engine for AToM3',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (479,'Scheduling Algorithm for Embedded Systems',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (480,'Energy-efficient Schedules for Embedded Systems',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (481,'Mining Execution Traces',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (483,'Biological Graph Mining',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (485,'Ontwerp en implementatie GPU gebaseerde algoritmen voor tomografie',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (486,'Nano-FASTRA: desktop supercomputing voor elektronentomografie',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (490,'Semantische kennis uit Wikipedia',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (491,'Visual Pattern Mining',3,FALSE);
insert into project (projectID, title, maxStudents, active) values (492,'Eindwerken Agfa Graphics',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (493,'Qt for VST',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (498,'Bewegingscorrectie bij computer tomografie',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (500,'Domain-Specific Modelling and Model Transformation  for Google Android applications',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (501,'Modelling and Transformation for Non-Player Characters in massively multiplayer games',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (503,'Mijn docop: doctoraatsopleiding gedigitaliseerd',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (504,'Robot Monitoring and Control Library',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (505,'Object Representations in Computer Aided Design',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (506,'Designing experiments for the optimization of nano-material manufacturing',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (507,'The role of structure in service reliability',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (508,'Modeling a Network of Energy Transmission and Distribution',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (509,'Mathematics for Smart Power ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (514,'Eclipse Plugin for Click Modular Router Development',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (515,'Deploying and XMPP architecture for server monitoring and management',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (516,'BRDF modeling for efficient photorealistic computer graphics',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (517,'Priority in Multiple Access Systems using Combinatorial Designs',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (518,'L-systems and Computer Graphics',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (519,'Algorithms for Flow Network Problems',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (525,'Building Hybrid Clouds with Amazon EC2 and Google AppEngine',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (526,'Limitations and opportunities for interactive applications on cloud resources ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (528,'Evaluating the performance of continuations ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (529,'Further development and deployment of a self-recovering SunSPOT testbed',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (530,'Artificial Intelligence for Lego Mindstorms Robots',5,TRUE);
insert into project (projectID, title, maxStudents, active) values (531,'Querying music score databases',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (532,'DataDia - Poussenier bvba',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (533,'Location based public transport planning on Android',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (534,'Forest growth prediction',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (535,'Web-based GUI builder',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (536,'Suitablility evaluation of the Azure Cloud Framework for scientific applications',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (537,'Optimizing instance type selection and application scaling in IaaS clouds',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (541,'A Market Design for IaaS Cloud Resources',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (542,'A Broker for Cost-efficient QoS aware resource allocation in EC2',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (543,'Dynamic Pricing for Desktop Clouds',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (544,'Het toevoegen van een forum structuur in de chaos van mailing lists',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (552,'Recognition of COBOL Control-Flow Patterns and Mapping to  OO-Constructs [with industrial partner]',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (553,'Mapping COBOL Data Types OO-Constructs  [industrial partner]',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (556,'Implementing a virtual network architecture using XMPP',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (557,'Unifying Modelica and Meta-Modelling',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (559,'Statechart synthesis of SVG/Ajax Web user interfaces',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (561,'Epsilon Object Language compiler',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (562,'Web-based text editor for Writing research',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (563,'Business Process Modelling',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (564,'Petri Net analysis',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (565,'Meta-Modelling and Transformation Environment',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (566,'Model Differencing',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (568,'Mapping transformation rules onto database queries',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (570,'Empowering knowledge computing with variable selection (for regression)',3,FALSE);
insert into project (projectID, title, maxStudents, active) values (571,'Link prediction in text',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (574,'Cluster implementatie van OpenCL',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (576,'RAFT Services',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (577,'Performance of Random Access Systems',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (578,'Netwerkbeveiliging door het combineren van beveiligingstechnieken',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (579,'Cartification',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (580,'Pattern Set Mining',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (582,'Dependability Analysis of WSDM-enabled Web Services',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (583,'Logisim naar Verilog vertaler',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (584,'FPGA implementatie van een Logisim ontwerp',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (587,'Ontwerp en implementatie van een software applicatie voor codificatie van medische ingrepen',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (588,'Opslag van patiÃ«nt-monitoring gegevens voor wetenschappelijk onderzoek',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (591,'Evaluatie van algoritmes voor de-identificatie van elektronische patiÃ«ntendossiers',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (592,'Exploring the state-of-the-art in SOA security',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (595,'Computer Aided Design tools voor robotarm sturing',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (596,'Grafische module voor het VirtualLeaf framework.',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (597,'Een individu-gebaseerd model voor de simulatie van de H1N1 pandemie in BelgiÃ«',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (598,'Cloud simulator in Java',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (599,'Meta-data based file archiving',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (602,'Instant Messenger Plugin for Cloud Logging',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (605,'Reengineering van de ESP website',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (606,'Smartphone Webservice plugin voor Eclipse',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (608,'Fast Rendering of Duplo Style Computer Graphics',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (611,'Designing a Hybrid Cloud for Scientific Computing ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (612,'Instrumentation of Xen VMs for efficient VM scheduling and capacity planning in hybrid clouds',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (613,'Computer graphics: irregular Z-buffering',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (614,'VM image distribution and migration in Desktop Clouds',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (615,'Brute-force Model space exploration for linear regression and variable selection on GPUs ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (616,'Exploring the state-of-the-art in distributed transaction programming (SOA)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (617,'Adaptive User Interfaces',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (621,'Model checking aspect-oriented programs',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (622,'Model checking role-oriented programs',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (623,'Estimating quality of experience in Human-Computer Interactions',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (624,'Java integratie in Groove',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (625,'Radio resource management in heterogeneous LTE networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (626,'The power of two paths in grid computing networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (627,'Multi-server queues with Markovian arrivals and general customer impatience',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (628,'Virtual Autonomic Robotic Systems and Environments',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (629,'Generatie van Cascading Style Sheets uit afbeeldingen',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (630,'Web technologies as enablers for SOA front-ends (e.g. AJAX)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (636,'Energy Efficient Data Center Scheduling',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (637,'Evaluating Price Setting Policies for Cloud Providers',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (638,'Automated Benchmarking of Virtualized Environments',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (639,'Optimistic Parallel and Distributed Discrete Event Simulation',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (640,'A Tracing Framework for Discrete-Event Simulations',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (641,'Evaluation and implementation of Event Queue ADTâ€™s',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (642,'Dependable, lightweight and service-oriented applications on smartphones',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (643,'Geautomatiseerde selectie van patiÃ«nten voor klinische studies',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (644,'Het gebruik van data mining en statistische technieken voor kwaliteitscontrole van medische gegevens',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (645,'Identificatie van risico groepen voor colorectale kanker met behulp van data mining methoden',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (653,'Network Security in IPv6 Networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (654,'Enhanced IPv6 support in the Click Modular Router',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (655,'TCP support in the Click Modular Router',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (656,'Recommender Systems',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (657,'Social network analysis',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (658,'Mining Train Delay Data',4,TRUE);
insert into project (projectID, title, maxStudents, active) values (659,'Approximate Instant Pattern Mining',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (660,'Python-like Human-Usable Textual Notation (HUTN)',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (661,'Textual transformation language for AToMPM',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (662,'Semi-automated migration of modelling artefacts',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (663,'Hybrid concrete syntax of modelling languages',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (664,'Rule-based Modelling of Non-Player Character (NPC) Behaviour ',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (665,'Transforming Statecharts to Petri Nets',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (666,'Domain-Specific Modelling and Model Transformation to support Collaborative Work on Android',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (668,'The future of data downloads: sparse signal processing',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (669,'Hyperspectral modelling',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (670,'Numerieke benaderingsleer in de praktijk: rol van de alternatiestelling',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (671,'Hyperspectraalbeelden',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (673,'NodeBox OpenGL draw performance',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (674,'NodeBox scene graph: raw performance',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (675,'NodeBox 2: parallelization',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (676,'Robuuste detectie en reconstructie van beschadigde digitale beeldbestanden',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (677,'Resource management and pricing in desktop clouds',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (679,'Reinforcement learning for decision support',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (684,'Website Browser Compatibility Analysis Toolkit',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (685,'Advanced spot market manager for Amazon EC2',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (686,'Custom form layouts',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (687,'Uniform Template Engine',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (688,'Automatisch schalen van een hybride webinfrastructuur',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (690,'Web technologies as enablers for SOA front-ends (e.g. AJAX)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (691,'iPad apps voor mensen met beperkingen',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (693,'Illustrating graph algorithms using Metapost',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (694,'Interactief data minen - Kinect',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (696,'Uitbreiding SNIPER',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (697,'Implementatie incrementeel pattern mining algoritme',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (698,'An Investigation of Cloud Contingency Solutions for SMEs',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (699,'Extending Scientific Compute Clusters with Cloud Infrastructure',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (700,'A unified, pluggable Git daemon',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (702,'An OMF wireless testbed',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (703,'IkHebEenVraag.be: improving the user experience using  [AI|DM|ML|NLP] techniques',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (706,'Vertaling van Logisim Logische ontwerpen naar DEVS',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (707,'A demo-visualization framework for PCAP files',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (708,'Videotheek admin applicatie',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (709,'Role Playing Game Maker',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (711,'Elektronisch Bibliotheeksysteem',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (712,'Evaluating built-in Xen metrics for performance modeling',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (713,'Smarter copy-pasting with aspects, and vice versa',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (714,'Integrating Groove into Java, and vice versa',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (715,'Aspect-oriented graph transformation',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (716,'Customer Tool Support for Trading off Cost and QoS in IaaS Service Procurement',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (719,'Process Migration in Discrete-Event Simulations with Conservative Time Synchronization',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (720,'Optimal Packing of Event Simulation Cores on Distributed Computing Platforms',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (721,'Cost-efficient Procurement of IaaS Services with Multiple Tariff Structures ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (723,'Hybrid Clouds for Flexible Batch Workload Processing',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (724,'Optimal ADT selection for Discrete-Event Simulation',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (726,'Analysis of time-related properties in graph transformations',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (730,'Wi-Fi interference mitigation  ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (732,'Development of Wi-Fi analysis application on a PC',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (733,'Wi-Fi coverage improvement through high power TX',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (734,'Building an EAP-SIM authenticated network',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (737,'Algorithms for Optimizing Costs of Electrical Vehicle Charging Tasks in Smart Grids',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (742,'Anthropometrics 2.0',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (743,'Overhead analysis of LXC on embedded devices ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (747,'Netmap on embedded systems',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (748,'A study of BMX',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (749,'A DLEP implementation in Click',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (754,'Hybrid Clouds for Flexible Batch Workload Processing',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (756,'Migration of an existing JavaEE mCommerce application to a cloud-based solution.',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (757,'Migratie van bestaande mobile marketing SaaS software naar een cloud-gebaseerde oplossing',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (759,'Algorithms for Optimizing Costs of Electrical Vehicle Charging Tasks in Smart Grids',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (760,'Garbage Collection and Block-mapped Flash Translation Layers in Solid State Drives',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (761,'Hit rates of web caching algorithms',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (762,'Vergelijking en benchmarking MAC protocollen van RFID en WSN technologieÃ«n t.o.v. DASH7 Mode 2 Draft',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (763,'Literature review on cost-efficient scheduling',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (764,'Resource management and pricing in desktop clouds',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (765,'Self-learning in digital pathology [industrial partner]',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (766,'Modeling of service-oriented communities',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (767,'Modular reasoning in OOP: Static checking of the Liskov substitution principle',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (768,'Aspect-oriented anything: Towards modular languages',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (769,'Aspect-oriented software in practice',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (770,'Interface Design for Trading off Cost and QoS in IaaS Service Procurement',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (771,'Building a Cloud Resource Allocator for Amazon EC2',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (772,'Data mining op de annotatie van biologische expressie compendia',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (778,'Rule-based weak memory models',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (779,'A survey on and optimisation of user profiles for network utilisation',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (780,'Development of a home automation system',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (781,'Automated testing for a home internet gateway',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (783,'In-home technology  evaluation kit',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (784,'WLAN throughput estimation',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (785,'Development of Wi-Fi analysis application on a PC',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (796,'Digital library of mathematical functions',3,TRUE);
insert into project (projectID, title, maxStudents, active) values (797,'Sparse methods for the bandwidth crisis',3,TRUE);
insert into project (projectID, title, maxStudents, active) values (798,'Pitch recognition / Chord characterization',3,TRUE);
insert into project (projectID, title, maxStudents, active) values (799,'Sparse bio-imaging techniques',3,TRUE);
insert into project (projectID, title, maxStudents, active) values (801,'HPC system management',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (805,'Residential Load Scheduling in Smart Grids',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (806,'Design and analysis of block- and hybrid-mapped FTLs in flash-based SSDs ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (807,'The impact of trimming on the performance of garbage collection algorithms in flash-based SSDs.',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (808,'Approximation methods to compute the hit rate in web caches',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (809,'Comparison of Pull and Push Strategies for Large  Distributed Heterogeneous Neworks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (811,'Anthropometrics 2.0: vervolgtraject',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (813,'Web technologies as enablers for SOA front-ends (e.g. AJAX)',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (814,'IkHebEenVraag.be: improving the user experience using  [AI|DM|ML|NLP] techniques',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (819,'Advanced network stack for Proxmox Virtualisation Environment',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (820,'Models and Representations for Fractal Social Organizations',4,TRUE);
insert into project (projectID, title, maxStudents, active) values (823,'RTSP low-resolution video streaming, its visualisation and interoperability analysis',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (826,'Home Femto SON',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (829,'(Parallel and Distributed) Discrete-Event Simulation of Smart Grids',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (830,'Data Analysis and Presentation for Preference Elicitation and Resource Management in Smart Grids',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (838,'Evolutie van gekarakteriseerde netwerken / Evolution of characterised networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (839,'Integration of item set mining in the open source Pymol tool',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (840,'Integration and representation of expression data in network analysis tools',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (842,'Large Scale Data Management for Smart Grids',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (843,'Frequent Itemset Mining for Big Data',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (844,'High-Dimensional Data Analysis',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (845,'Sampling Pattern Sets',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (846,'Fault Tolerant Pattern Set Mining',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (847,'Opinion mining',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (849,'Visualisation of realistic data for cellular network simulations',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (851,'Twitter Reommendation',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (852,'Foursquare Recommender',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (853,'New User Problem in Recommendation Systems',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (854,'Negative Recommendation Systems',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (855,'Facebook Unmask App',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (857,'GUI development for high dimensional data analysis',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (865,'Developing a web interface for creating scenario instances in a user-friendly way',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (866,'Predict Maintenance Time',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (867,'Internship opportunity at Philips research',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (868,'Whatâ€™s in the air? Compressive sensing for cognitive radio.',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (873,'Design of location-aware Google Glassware',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (874,'Design of gesture-enabled and location-aware smart home applications',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (875,'Deployment and analysis of a security honeypot in the UAntwerp network',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (876,'Achieving service-level fairness using game theoretic mechanism design',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (877,'Cognitive and large-scale self organizing wireless hotspots',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (878,'Building multi-homed networks using network virtualization',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (880,'Monitoring framework for wireless hotspots',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (882,'Design of gossiping protocols on low-cost wearables',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (883,'Large-scale data analysis in access networks',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (888,'Game theoretical cow trading',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (891,'State space optimization of graph transformation systems',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (896,'Direction of Arrival Estimation in Array Signal Processing',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (897,'Exploration of sparse non-linear system solvers and integration in a scient. prod. code ALEPH2',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (898,'Scientific data management in ALEPH2, conversion of flat to HDF5 format and design of data hierarchy',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (899,'Wireless monitoring platform for mobile densely crowded areas',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (900,'Design and implementation of an augmented reality-based multiplayer game using fine-grained localiza',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (901,'Towards the synthetic human: comparing simulated networks to reality',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (902,'From Facebook to cell: Are protein networks social? ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (904,'Visualizing interesting itemset properties with D3.JS',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (908,'Implementation of a significant subgraph mining method',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (909,'Interactive and scalable pattern mining on big life science data in the cloud',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (910,'Anomaly mining for the discovery of unknown protein modifications',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (911,'Improvement of protein identification pipelines by systemic contaminant monitoring',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (912,'Multi-abstraction, Multi-formalism Modelling and Simulation',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (914,'A Lossless sniffer for IEEE 802.15.4 networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (915,' Improving the wireless module in the ns-3 network simulator',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (916,'Exploring hazardous environments with unmanned vehicles',3,FALSE);
insert into project (projectID, title, maxStudents, active) values (917,'Multi-hop routing algorithm using machine learning',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (918,'Helping visually impaired people boarding public transport',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (919,'Limb movement detection for fully mobile and immersive VR using the Oculus Rift',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (920,'A low-latency and reliable wireless network for multiplayer mobile VR using the Oculus Rift',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (922,'SDN routing prediction',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (923,'Drone Drawings',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (924,'A study of intercloud latency',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (925,'IoT interoperability in A City',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (926,'WiFi dimensioning in A City',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (927,'Modeling a Graphical User Interface for AToMPM',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (929,'Indoor Localization for Evacuation Guidance',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (933,'Visualisation of an algorithm for improving handover decisions in a nomadic network',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (934,'Predictive analytics in industrial environments [industrial partner]',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (935,'Entity profiling and recommendation in an industrial context [industrial partner]',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (936,'Secure mobile development',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (937,'Automated planning of ISP core network expansions',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (938,'ZooKeeper',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (939,'Stress testing Amplidataâ€™s storage backend',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (940,'Make mobile apps less annoying by measuring and decreasing the irritation factor',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (941,'Increase good app behaviour by involving his or her buddies ',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (942,'Individu gebaseerde simulatie toegepast op epidemiologische problemen',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (943,'Detection of seizures in electroencephalography recordings',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (944,'Performance benchmarking en optimalisatie van een C++ PDEVS simulator',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (945,'Indoor Localisation With Wireless Technologies',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (946,'A bayesian noise model for biological expression data',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (948,'Temporal mining of quality control data',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (950,'Deep learning for peptide identification from mass spectra',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (952,'Efficient solvers for constrained spherical deconvolution of diffusion MRI',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (955,'Statistische modelering van vormen',3,TRUE);
insert into project (projectID, title, maxStudents, active) values (956,'Empirical Study on Test Refactoring',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (957,'Mutation Testing of C++ Programs ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (958,'Gamification of Test Development Using Mutation Testing',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (959,'OpenFlow-based multi-homed hybrid home networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (960,'Deep learning MHC binding preferences',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (961,'Metric for determining test refactoring candidates',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (962,'BLE localization in smart homes',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (963,'Wi-Fi / LTE loadbalancer for Android devices',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (964,'Security in Smart Cities',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (965,'Feasibility study of Time Series Databases for Newtec Dialog',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (966,'Anomaly detection in a telecommunication system',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (967,'Auditing system to efficiently capture user actions on a system',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (968,'Resource allocation and network performance in a containerised environment',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (969,'IO performance comparison of various optimisation options on a specific Hardware set',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (970,'Realtime behaviour in a virtualised environment',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (971,'Lightweight network tester',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (973,'Energy consumption modeling in OpenWSN: An open source protocol stack for the Internet of Things ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (974,'Software security engineering for financial institutions',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (975,'Power management Implementation in NS-3 for Wi-Fi HaLow dense IoT networks',2,FALSE);
insert into project (projectID, title, maxStudents, active) values (976,'Analysis, diagnosis and monitoring of 6LoWPAN networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (977,'using machine learning Techniques For Proactive Network Management',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (978,'Building Expert system for SIzing servers to fit an estimated load',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (979,'Load-balancing in high density large-scale Wi- Fi environments',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (980,'Distributed SDN based controller for client management in Wi-Fi',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (982,'Visualisation of client behaviour in managed Wi-Fi network',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (983,'Evaluating coordinated coexistence and access management for sub Ghz protocols',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (985,'Distributed clock synchronization for ultra-low power wireless sensor networks',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (986,'Implementation, evaluation and comparison of LoRaWAN transmission modes',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (987,'Individu-gebaseerd model voor de verspreiding van griep en mazelen in Vlaanderen',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (988,'Duplicate detection in business term descriptions',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (991,'Reducing bug handling overhead via machine learning [industrial partner]',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (992,'Onderzoek en ontwerp van een Single Page App designer',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (994,'The Monuments Men â€“ Actionable data from indoor air quality analysis',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (995,'The Monuments Men â€“ formal modelling of indoor air quality in view of preventive and proactive cultu',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (996,'Developing  a performant geographical distribution algorithm  [Industrial Partner]',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (997,'A GIS-based multi-criteria decision planning model [Industrial Partner]',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (998,'A theoretical study of repair-based detection of errors in data',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (999,'Experimental assessment of the quality of error detection and repairing methods.',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1001,'Lightweight OpenFlow',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1002,'Discovering Local Statistical Distributions using R',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1003,'Evaluation of future Wi-Fi technologies',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1004,'Providing network security in a resource-constrained cyclist network',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1005,'Security in the Internet of Things',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1006,'Prototyping a resource-constrained cyclist network',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1007,'Scheduling in a resource-constrained cyclist network',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1008,'Security on an interconnected embedded Linux device',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1009,'3D-model based on image fusion of LiDAR and Video camera mounted on a drone',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1010,'Develop an anomaly detection algorithm and implement it on an GPU-platform',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1011,'Explore innovative approaches to data-sharing in the mobile access network',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1012,'Bluetooth Low Energy (BLE) Indoor localization',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1013,'Wireless SDN based management framework on newer code base',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1014,'Increasing reliability in distributed SDN controller for wireless networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1015,'Distributed VR application using indoor wireless localization',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1017,'WiFi HaLow implementation in Time-Annotated Instruction Set Computer',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1018,'Generate and use a large-scale data-set for IoT experiments',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (1019,'Using block-chain to extend some cloud system funtionalities',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1020,'New test set for interaction graphs and evaluation of an algorithm',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1021,'Influence propagation in Location-based Social Networks: add influence propagation algo''s to demo',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1022,'Influence propagation in Location-based Social Networks: improve simulator and interactive browser',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1023,'Analyzing electron microscopic images',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1024,'Discrimination-aware data mining: explaining seemingly discriminatory models ',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1025,'Cycle detection in interaction graphs',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1026,'Identifying top-influencers in a financial network',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1027,'Handwritten text recognition using machine learning',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1028,'Sketch based algorithms: Experimental validation',2,TRUE);
insert into project (projectID, title, maxStudents, active) values (1030,'Design and implementation of a SDN/IoT solution',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1031,'Profile guided fuzz-testing on large scale applications [Industrial Partner]',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1033,'Design a VR acoustic room in Unity for testing 3D audio ',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1035,'Deep learning for mass spectra identification validation',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1036,'Empirical Study on Cross-Project Code Clones',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1037,'Using Bioinformatics Techniques for Code Clone Detection',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1038,'Life science multi-label graph classification',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1039,'Subgraph visualisation tool with 3d.js',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1040,'Viral protein life-cycle prediction',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1041,'TCR sequence data mining',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1043,'Predicting protein-protein interactions between pathogens and their hosts',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1045,'Deep learning applied to graph drawing and network visualisation',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1046,'Reverse Engineer Google Wi-Fi',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1047,'Implementation of a controller to manage heterogeneous networks',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1048,'Interactive raw pattern mining',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1049,'Predicting user behaviour',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1050,'Creating resilient networks using machine learning ',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1052,'Evaluating and comparing state-of-art reinforcement learning algorithms',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1055,'Policy-based TSCH scheduling',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1057,'TSCH scheduling in industrial areas',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1058,'Optimizing 6TiSCH performance in the sub-1GHz band',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1059,'Implementation and evaluation of 60GHz handovers',1,TRUE););
insert into project (projectID, title, maxStudents, active) values (1062,'Optimizing the energy efficiency of Wi-Fi HaLow for the IoT',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1063,'Hierarchical Sequence Memory',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1064,'Multi-technology and multi-technique wireless indoor localization',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1065,'Enabling SDN capabilities in heterogeneous 6LoWPAN networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1067,'Optimizing mobile networks for IoT devices using NB-IoT',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1069,'Optimizing 6LoWPAN networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1070,'Predicting latency in heavily interfered wireless networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1071,'Distributed SDN controller for heterogeneous wireless networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1073,'Target Propagation for Deep Neural Networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1074,'Modelling a fibbing-based API for 6LoWPAN networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1075,'Design and implement YANG/COMI models for 6LoWPAN networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1079,'Creating resilient networks using machine learning - location prediction',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1080,'Multipath TCP in NS-3 network simulator',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1081,'Implementation of ORCHESTRA in NS-3 network simulator',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1082,'Flexible auto-encoder for semi-supervised deep learning',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1083,'Efficient Generative Adversarial Nets (GANs)',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1084,'Advanced NFC communication with nurse call devices ',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1085,'IoT sensor network for passenger counting on trains',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1086,'Secure BLE connectivity for patient monitoring system ',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1087,'Linking Identity Server 4 to External Authentication services ',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1088,'Wireless but reliable connectivity for nurse call ',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1089,'CityLab and The Things Network',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1090,'Octa OTA update via NB-IoT/Cat-M1',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1091,'CityLab does Orchestra',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1092,'CityLab learns',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1093,'CityLab5G',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1094,'CityLabCl',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1095,'D7 hardware on OpenWSN',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1096,'Deep learning to classify data flows in Wi-Fi and LTE networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1098,'Create a RL agent for flow scheduling in an MF-TDMA network',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1099,'Enabling battery-less IoT devices',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1100,'Nanoscale communications for wirelessly programmable robotic materials',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1101,'Managing flexible multimodal IoT devices',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1102,'Over-the-air firmware updates for IoT devices over cellular networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1103,'MAC protocol analysis on IEEE 802.11 networks',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1104,'Implementation of Next Generation Interfaces for 5G system functional split',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1105,'Distributed Hierarchical Temporal Memory in NuPIC',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1106,'Developing and Evaluating a Behaviour Based Code Coverage Metric',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1107,'Behaviour Based Control Systems for (Semi-)Autonomous Drone Flight',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1108,'data mining en machine learning  op classificaties door citizen scientists',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1109,'Data Generator for Anomaly Detection in Business Processes',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1110,'NodeBox OpenGL draw performance',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1111,'NodeBox 2: parallelization',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1112,'Energy consumption modeling in OpenWSN: An open source protocol stack for the Internet of Things ',1,FALSE);
insert into project (projectID, title, maxStudents, active) values (1113,'Visual exploration of log files',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1114,'Reducing noise of mutation testing a.k.a ranking mutants according to their importance',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1115,'Automatic test expansion for mutation testing',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1116,'Multilingual Embeddings in NLP models',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1117,'Expression Generation for Chatbot NLP''s',1,TRUE);
insert into project (projectID, title, maxStudents, active) values (1118,'Messaging Broker C++',1,TRUE);
