insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (1,'No research group','NONE','y', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (2,'Modelling of Systems and Internet Communication','MOSAIC','y', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (3,'Advanced Database Research and Modelling','ADReM','y', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (5,'Lab On REengineering','LORE','n', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (6,'Computational Mathematics','CMA','y', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (7,'Emerging Computational Techniques','ECT','n', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (8,'Formal Techniques in Software Engineering','FOTS','n', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (9,'Computational Modeling and Programming (MOASIC)','MOSAICCOMP','n', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (10,'Computer Modeling and Simulation','COMS','n', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (11,'Antwerp Group on Robust and Applied Statistics','AGORAS','y', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (12,'Intelligent Systems Laboratory','ISLAB','n', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (13,'Mathematics','MATH','y', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (14,'Visielab','VISIELAB','y', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (15,'Modelling, Simulation and Design Lab','MSDL','n', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (16,'STudentenadministratie En Roostering','STER','n', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (17,'Antwerp Systems and software Modelling','ANSYMO','y', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (18,'Departement Wiskunde-Informatica (overkoepelend)','DWI','y', NULL, NULL, NULL);
insert into researchGroup (groupID, name, abbreviation, active, discipline, address, telNr) values (19,'Internet & Data Lab','IDLab','y', NULL, NULL, NULL);
