insert into research_groups (id, name, abbreviation, active) values (1,'No research group','NONE','y');
insert into research_groups (id, name, abbreviation, active) values (2,'Modelling of Systems and Internet Communication','MOSAIC','y');
insert into research_groups (id, name, abbreviation, active) values (3,'Advanced Database Research and Modelling','ADReM','y');
insert into research_groups (id, name, abbreviation, active) values (5,'Lab On REengineering','LORE','n');
insert into research_groups (id, name, abbreviation, active) values (6,'Computational Mathematics','CMA','y');
insert into research_groups (id, name, abbreviation, active) values (7,'Emerging Computational Techniques','ECT','n');
insert into research_groups (id, name, abbreviation, active) values (8,'Formal Techniques in Software Engineering','FOTS','n');
insert into research_groups (id, name, abbreviation, active) values (9,'Computational Modeling and Programming (MOASIC)','MOSAICCOMP','n');
insert into research_groups (id, name, abbreviation, active) values (10,'Computer Modeling and Simulation','COMS','n');
insert into research_groups (id, name, abbreviation, active) values (11,'Antwerp Group on Robust and Applied Statistics','AGORAS','y');
insert into research_groups (id, name, abbreviation, active) values (12,'Intelligent Systems Laboratory','ISLAB','n');
insert into research_groups (id, name, abbreviation, active) values (13,'Mathematics','MATH','y');
insert into research_groups (id, name, abbreviation, active) values (14,'Visielab','VISIELAB','y');
insert into research_groups (id, name, abbreviation, active) values (15,'Modelling, Simulation and Design Lab','MSDL','n');
insert into research_groups (id, name, abbreviation, active) values (16,'STudentenadministratie En Roostering','STER','n');
insert into research_groups (id, name, abbreviation, active) values (17,'Antwerp Systems and software Modelling','ANSYMO','y');
insert into research_groups (id, name, abbreviation, active) values (18,'Departement Wiskunde-Informatica (overkoepelend)','DWI','y');
insert into research_groups (id, name, abbreviation, active) values (19,'Internet & Data Lab','IDLab','y');
